# Docs: https://fly.io/docs/reference/configuration/

app = "pokedextracker-nginx"
primary_region = "sjc"

[deploy]
  strategy = "rolling"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
